import AppKit

extension NSPasteboard.PasteboardType {
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let pasteLiteSelfMarker = NSPasteboard.PasteboardType("com.xia.PasteLite.self")
    static let pasteLiteInternal = pasteLiteSelfMarker
    static let legacyColor = NSPasteboard.PasteboardType("NSColor pasteboard type")
    static let legacyTIFF = NSPasteboard.PasteboardType("NeXT TIFF v4.0 pasteboard type")

    static let pasteLiteReadableTypes: [NSPasteboard.PasteboardType] = [
        .fileURL,
        .URL,
        .string,
        .color,
        .legacyColor,
        .png,
        .tiff,
        .legacyTIFF
    ]

    static let pasteLiteImageTypes: Set<NSPasteboard.PasteboardType> = [
        .png,
        .tiff,
        .legacyTIFF
    ]

    static let pasteLiteColorTypes: [NSPasteboard.PasteboardType] = [
        .color,
        .legacyColor
    ]

    static let pasteLiteIgnoredTypes: Set<NSPasteboard.PasteboardType> = [
        .transient,
        .concealed,
        .autoGenerated,
        .pasteLiteSelfMarker
    ]

    var isPasteLiteReadable: Bool {
        Self.pasteLiteReadableTypes.contains(self)
    }

    var isPasteLiteIgnored: Bool {
        Self.pasteLiteIgnoredTypes.contains(self)
    }
}

extension NSPasteboard {
    var pasteLiteHasIgnoredTypes: Bool {
        if (types ?? []).contains(where: { $0.isPasteLiteIgnored }) {
            return true
        }

        return pasteboardItems?.contains(where: { $0.pasteLiteHasIgnoredTypes }) ?? false
    }
}

extension NSPasteboardItem {
    var pasteLiteHasIgnoredTypes: Bool {
        types.contains(where: { $0.isPasteLiteIgnored })
    }

    @discardableResult
    func setPasteLiteSelfMarker() -> Bool {
        setString("1", forType: .pasteLiteSelfMarker)
    }
}

@MainActor
enum PasteLitePasteboardWriteGuard {
    private static var ignoredChangeCount: Int?
    private static var ignoredPasteboardName: NSPasteboard.Name?

    static func markSelfWrite(on pasteboard: NSPasteboard) {
        ignoredChangeCount = pasteboard.changeCount
        ignoredPasteboardName = pasteboard.name
    }

    static func consumeIfSelfWrite(changeCount: Int, on pasteboard: NSPasteboard = .general) -> Bool {
        guard ignoredPasteboardName == pasteboard.name else { return false }
        guard ignoredChangeCount == changeCount else {
            if let ignoredChangeCount, changeCount > ignoredChangeCount {
                self.ignoredChangeCount = nil
                ignoredPasteboardName = nil
            }
            return false
        }

        ignoredChangeCount = nil
        ignoredPasteboardName = nil
        return true
    }
}
